server:
  port: 8182
spring:
  application:
    name: split-with-room-mates
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Bholahi@123
    url: jdbc:mysql://dbsraj.mysql.database.azure.com/bill_buddy
    username: raj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
